version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgresql
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - /Users/chaplin/workspace/:/var/lib/postgresql/data
